### ISSUE TITLE
Remove git-lfs?

### ISSUE THREAD

**Issue by kylinroc** [microsoft/FluentDarkModeKit#70]
I don't think enable git-lfs for an image which will almost never change and let users do some extra setups is worth.

How about just remove git-lfs?

cc @icodesign

**Comment by imWildCat** [comment]
Can we refer to this image by dragging it into issues textarea then get the URL of this image?

**Comment by icodesign** [comment]
I would say this is more of an Apple issue. I encountered it a lot when using other packages as well. Even we removed this file, there's no guarantee that we wouldn't add another file and it's not a good idea to ask contributors to stop using Git LFS (the right thing). 

If you're going to use SPM, you're gonna face this issue until Apple fix it. Otherwise, Carthage/CocoaPods are still options.

 I tend not to fix from our side as long as we've provided enough information.

**Comment by eyvallah** [comment]
Removing LFS might not be very viable, since it is already in the history. If there are devs who are trying to fetch an earlier version from Xcode, the same thing would still happen.

**Comment by imWildCat** [comment]
Another reference is that: `ResearchKit` does have git-lfs: https://github.com/researchkit/researchkit

**Comment by kylinroc** [comment]
It seems ResearchKit will ignore lfs files for clone and pull: https://github.com/ResearchKit/ResearchKit/blob/master/.lfsconfig

Looks like a nice solution.

**Comment by icodesign** [comment]
TIL. That's decent.

**Comment by eyvallah** [comment]
I created a branch with [this commit](https://github.com/microsoft/FluentDarkModeKit/commit/d830079ec195c8e33a73117f74b344a21760520c), however the issue did not get resolved when I was using Xcode to fetch it as a swift package (specifying the branch name as exclude-lfs-on-clone).

The difference that creating .lfsconfig excluding files makes is that it will prevent lfs files being resolved, but git-lfs will still get called, I think due to .gitattribute.

There might not be a way to work around this on machines without git-lfs.

**Comment by kylinroc** [comment]
> I created a branch with [this commit](https://github.com/microsoft/FluentDarkModeKit/commit/d830079ec195c8e33a73117f74b344a21760520c), however the issue did not get resolved when I was using Xcode to fetch it as a swift package (specifying the branch name as exclude-lfs-on-clone).
> 
> The difference that creating .lfsconfig excluding files makes is that it will prevent lfs files being resolved, but git-lfs will still get called, I think due to .gitattribute.
> 
> There might not be a way to work around this on machines without git-lfs.

I guess Xcode will clone all branches and check out to your specified branch, only one branch with `.lfsconfig` seems not enough.

**Comment by eyvallah** [comment]
Now I'm having no issue with the spm inside latest Xcode now even without the symbolic link hack, lfs files were simply not resolved and that is ideal. But I'm not sure if it works for everyone now.

**Comment by icodesign** [comment]
I checked and still need the hack.
![image](https://user-images.githubusercontent.com/1148601/83593482-716b8680-a58f-11ea-95e0-6c0aee18953d.png)

**Comment by icodesign** [comment]
The error above is because that the script Apple is using doesn't include `/usr/local/bin` in its path while `git-lfs` is put under that path for most of us.

I think we can skip it since it's not an issue of this repo.

![image](https://user-images.githubusercontent.com/1148601/83593840-4a618480-a590-11ea-8e39-79384feb7ad8.png)

**Comment by eyvallah** [comment]
Let's close this for now.
